name       : kodi-pvr-iptvsimple 
version    : 2.4.14
release    : 1
source     :
    - https://github.com/kodi-pvr/pvr.iptvsimple/archive/2.4.14-Krypton.tar.gz : 329bd71e5c786d7b037bf5fd103ee4abff892afc6e5186a5d0a797194a8c4c7c
license    : GPL-2.0-or-later
component  : desktop.multimedia
summary    : Kodi's IPTV Simple client addon
description: |
    IPTV Live TV and Radio PVR client addon for Kodi
builddeps  :
    - pkgconfig(kodiplatform)
    - pkgconfig(p8-platform) 
    - kodi-devel
rundeps     :
    - kodi
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
